"""Generate the deterministic sample outputs used across the documentation.

    python scripts/capture_samples.py            # write docs/samples/*
    python scripts/capture_samples.py --check    # fail if the files are stale

The script creates a throwaway ``<database>_samples`` database next to the
configured one, migrates it, runs four scripted scenarios against it, writes
normalised outputs and drops the database again. It never touches the configured
database, and the only network-capable piece (the retry sample) goes through a
mocked transport, so regenerating is offline and repeatable.

Determinism rules: the pipeline's clock is frozen, run ids are replaced with a
placeholder, timestamps are dropped from the captured tables, and the DSN is
masked. Rerun the script after a behaviour change and commit the diff - that diff
is the documentation evidence for the change.
"""

from __future__ import annotations

import argparse
import io
import json
import random
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any

# The script uses the recorded-fixture helpers from the test tree, so make the
# repository root importable no matter where the script is invoked from.
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:  # pragma: no cover - import plumbing
    sys.path.insert(0, str(REPO_ROOT))

import httpx
import respx
import sqlalchemy as sa
from sqlalchemy.engine import Engine
from tests.support import FakeWeatherSource, build_series, payload_for_recent_hours

from adcp.api.open_meteo import OpenMeteoClient
from adcp.cli.collect_cmd import exit_code_for, render_summary
from adcp.config import Settings
from adcp.db.engine import create_engine_from_settings, dispose_engine
from adcp.db.migrations.runner import upgrade
from adcp.db.repository import LocationRepository
from adcp.db.tables import ingestion_run_errors
from adcp.errors import UpstreamServerError
from adcp.logging import configure_logging
from adcp.models.location import Location
from adcp.models.observation import ObservationSource
from adcp.models.run import RunSummary
from adcp.models.window import RecentWindow
from adcp.pipeline.service import CollectionService

#: Frozen clock so the windows, hour labels and counters never change.
FIXED_NOW = datetime(2026, 10, 1, 12, 37, tzinfo=UTC)
LOOKBACK_HOURS = 3
OVERLAP_HOURS = 2
FORECAST_URL = "https://api.open-meteo.com/v1/forecast"
PLACEHOLDER_DSN = "postgresql+psycopg://adcp:***@localhost:5432/adcp"
PLACEHOLDER_RUN = "<run_id>"

SAMPLE_LOCATIONS = (
    ("belgrade-rs", "Belgrade", Decimal("44.812500"), Decimal("20.437500")),
    ("reykjavik-is", "Reykjavik", Decimal("64.146600"), Decimal("-21.942600")),
)

_UUID = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
_TIMESTAMP = re.compile(r'"timestamp": "[^"]+"')
_DURATION = re.compile(r'"duration_ms": [0-9.eE+-]+')


@dataclass(frozen=True, slots=True)
class Sample:
    """One generated file."""

    name: str
    title: str
    content: str

    def render(self) -> str:
        body = (
            f"# generated by scripts/capture_samples.py - do not edit by hand\n# {self.title}\n\n"
        )
        return f"{body}{self.content.rstrip()}\n"


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Regenerate the documentation samples.")
    parser.add_argument("--output", type=Path, default=Path("docs/samples"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare against the committed samples instead of writing them.",
    )
    return parser.parse_args()


def scenario_settings(database_url: str) -> Settings:
    return Settings().with_overrides(
        database_url=database_url,
        env="local",
        ingest_lookback_hours=LOOKBACK_HOURS,
        ingest_overlap_hours=OVERLAP_HOURS,
        open_meteo_max_concurrency=2,
        open_meteo_max_attempts=2,
        open_meteo_backoff_initial_s=0.001,
        open_meteo_backoff_max_s=0.01,
    )


def _render(url: sa.engine.URL) -> str:
    """Render a SQLAlchemy URL with the password intact.

    ``str(URL)`` masks the password (it forwards to
    ``render_as_string(hide_password=True)``), so scripts that need a *usable*
    DSN must call this helper instead.
    """
    return url.render_as_string(hide_password=False)


def scratch_url(base: str, suffix: str = "_samples") -> str:
    url = sa.engine.make_url(base)
    return _render(url.set(database=f"{url.database}{suffix}"))


def _admin_engine(admin_base: str) -> sa.Engine:
    return sa.create_engine(
        _render(sa.engine.make_url(admin_base).set(database="postgres")),
        isolation_level="AUTOCOMMIT",
        connect_args={"connect_timeout": 5},
    )


def create_scratch_database(admin_base: str, name: str) -> None:
    admin = _admin_engine(admin_base)
    try:
        with admin.connect() as connection:
            connection.execute(sa.text(f'DROP DATABASE IF EXISTS "{name}"'))
            connection.execute(sa.text(f'CREATE DATABASE "{name}"'))
    finally:
        admin.dispose()


def drop_scratch_database(admin_base: str, name: str) -> None:
    admin = _admin_engine(admin_base)
    try:
        with admin.connect() as connection:
            connection.execute(sa.text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
    finally:
        admin.dispose()


def seed_locations(engine: Engine) -> dict[str, Location]:
    repository = LocationRepository(engine)
    seeded: dict[str, Location] = {}
    for slug, name, latitude, longitude in SAMPLE_LOCATIONS:
        record = repository.create(slug=slug, name=name, latitude=latitude, longitude=longitude)
        seeded[slug] = Location.from_record(record)
    return seeded


def storage_hours(count: int = LOOKBACK_HOURS) -> list[datetime]:
    end = FIXED_NOW.replace(minute=0, second=0, microsecond=0)
    return [end - timedelta(hours=offset) for offset in range(count, 0, -1)]


def collect(
    engine: Engine,
    settings: Settings,
    *,
    hours: int = LOOKBACK_HOURS,
    overrides: dict[datetime, dict[str, Any]] | None = None,
    failing: Sequence[str] = (),
) -> RunSummary:
    """Run one collection with a scripted source (no network)."""
    # The storage window starts at ``watermark - overlap`` (capped by the
    # lookback), so widen both to match the scripted payload - otherwise the
    # extra hours are skipped as out-of-window instead of being validated.
    scenario = settings.with_overrides(
        ingest_lookback_hours=hours,
        ingest_overlap_hours=hours,
    )
    moments = storage_hours(hours)

    def responder(location: Location, source: ObservationSource, _window: Any) -> Any:
        if location.slug in failing:
            msg = "Open-Meteo returned a server error (HTTP 503)"
            raise UpstreamServerError(msg, status_code=503, endpoint=FORECAST_URL)
        return build_series(
            location=location,
            source=source,
            moments=moments,
            observation_overrides=overrides,
        )

    service = CollectionService(
        scenario,
        source=FakeWeatherSource(responder=responder),
        engine=engine,
        now=lambda: FIXED_NOW,
        clock=lambda: 0.0,
    )
    return service.run(trigger="cli")


def summary_json(summary: RunSummary) -> str:
    payload = summary.as_dict()
    payload["run_id"] = None if payload["run_id"] is None else PLACEHOLDER_RUN
    for field in ("started_at", "finished_at"):
        payload.pop(field, None)
    payload.pop("duration_ms", None)
    return json.dumps(payload, indent=2, sort_keys=True)


def render_table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    """A psql-like aligned table, without the psql runtime."""
    columns = [[str(cell) for cell in row] for row in rows]
    widths = [len(header) for header in headers]
    for row in columns:
        widths = [max(width, len(cell)) for width, cell in zip(widths, row, strict=True)]
    lines = [" | ".join(headers[index].ljust(widths[index]) for index in range(len(headers)))]
    lines.append("-+-".join("-" * width for width in widths))
    lines.extend(
        " | ".join(row[index].ljust(widths[index]) for index in range(len(headers)))
        for row in columns
    )
    return "\n".join(lines)


def count_rows(engine: Engine) -> int:
    with engine.connect() as connection:
        return int(connection.execute(sa.text("SELECT count(*) FROM weather_hourly")).scalar_one())


def cli_text(summary: RunSummary) -> str:
    """The text block `adcp collect` prints, minus the volatile run id/duration."""
    counts = summary.counts
    rows = (
        f"received {counts.rows_received}, inserted {counts.rows_inserted}, "
        f"updated {counts.rows_updated}, unchanged {counts.rows_unchanged}, "
        f"rejected {counts.rows_rejected}, skipped {counts.rows_skipped}"
    )
    return "\n".join(
        [
            f"Collection complete: {summary.status.value}",
            render_summary(summary).rstrip(),
            f"run_id        {PLACEHOLDER_RUN}",
            f"locations     {counts.locations_succeeded} ok, "
            f"{counts.locations_failed} failed, {counts.locations_total} requested",
            f"rows          {rows}",
            f"requests      {counts.requests_made} made, {counts.requests_retried} retried",
            f"duration_ms   {summary.duration_ms}",
            f"summary       {summary.error_summary or '(all good)'}",
        ],
    )


def run_history_sample(engine: Engine) -> str:
    statement = sa.text(
        "SELECT status, locations_succeeded || '/' || locations_total AS locations,"
        " rows_received, rows_inserted, rows_updated, rows_unchanged, rows_rejected"
        " FROM ingestion_runs ORDER BY started_at",
    )
    with engine.connect() as connection:
        rows = connection.execute(statement).all()
    return render_table(
        ("status", "locations", "received", "inserted", "updated", "unchanged", "rejected"),
        rows,
    )


def observation_sample(engine: Engine) -> str:
    statement = sa.text(
        "SELECT l.slug, w.source, count(*) AS rows,"
        " min(w.observed_at)::date AS first_day, max(w.observed_at)::date AS last_day,"
        " coalesce(sum(w.revision_count), 0) AS revisions"
        " FROM weather_hourly w JOIN locations l ON l.id = w.location_id"
        " GROUP BY l.slug, w.source ORDER BY l.slug",
    )
    with engine.connect() as connection:
        rows = connection.execute(statement).all()
    return render_table(("slug", "source", "rows", "first_day", "last_day", "revisions"), rows)


def rejection_sample(engine: Engine, run_id: Any) -> str:
    statement = (
        sa.select(
            ingestion_run_errors.c.phase,
            ingestion_run_errors.c.error_type,
            ingestion_run_errors.c.error_code,
            ingestion_run_errors.c.message,
        )
        .where(ingestion_run_errors.c.run_id == run_id)
        .order_by(ingestion_run_errors.c.id)
    )
    with engine.connect() as connection:
        rows = connection.execute(statement).all()
    return render_table(("phase", "error_type", "error_code", "message"), rows)


def retry_sample(settings: Settings) -> str:
    """A retry log captured from the real client with a mocked transport."""
    # Full-jitter backoff draws its delay from the ``random`` module; seeding it
    # keeps the captured ``delay_s`` stable so the sample is byte-reproducible.
    random.seed(20_261_001)
    # The pipeline scenarios use a near-zero backoff to stay fast; the sample is
    # documentation, so use the shipped defaults to show a realistic delay.
    realistic = settings.with_overrides(
        open_meteo_max_attempts=3,
        open_meteo_backoff_initial_s=0.5,
        open_meteo_backoff_max_s=30.0,
    )
    buffer = io.StringIO()
    configure_logging(
        level="DEBUG",
        log_format="json",
        service="adcp",
        environment="sample",
        stream=buffer,
    )
    attempts = 0

    def responder(_request: httpx.Request) -> httpx.Response:
        nonlocal attempts
        attempts += 1
        if attempts == 1:
            return httpx.Response(503, text="temporarily unavailable")
        return httpx.Response(200, json=payload_for_sample())

    with respx.mock(assert_all_called=False) as router:
        router.get(FORECAST_URL).mock(side_effect=responder)
        with OpenMeteoClient(realistic, sleep=lambda _delay: None, now=lambda: FIXED_NOW) as client:
            client.fetch_hourly(
                location=Location(
                    slug="belgrade-rs",
                    name="Belgrade",
                    latitude=Decimal("44.812500"),
                    longitude=Decimal("20.437500"),
                ),
                source=ObservationSource.FORECAST,
                window=RecentWindow(past_days=1),
            )

    keep = {"api.request.started", "api.request.retry", "api.request.completed"}
    lines: list[str] = []
    for line in buffer.getvalue().splitlines():
        if not line.strip().startswith("{"):
            continue
        event = json.loads(line)
        if event.get("event") not in keep:
            continue
        event.pop("timestamp", None)
        event.pop("logger", None)
        lines.append(json.dumps(event, sort_keys=True))
    return "\n".join(lines)


def payload_for_sample() -> dict[str, Any]:
    return payload_for_recent_hours(lookback_hours=LOOKBACK_HOURS)


def watermark_sample(engine: Engine) -> str:
    statement = sa.text(
        "SELECT l.slug, m.source, m.last_observed_at FROM ingestion_watermarks m"
        " JOIN locations l ON l.id = m.location_id ORDER BY l.slug",
    )
    with engine.connect() as connection:
        rows = connection.execute(statement).all()
    return render_table(("slug", "source", "last_observed_at"), rows)


def build_samples(engine: Engine, settings: Settings) -> list[Sample]:
    seed_locations(engine)
    first = collect(engine, settings)
    second = collect(engine, settings)
    first_history = run_history_sample(engine)
    stored_rows = count_rows(engine)

    # A wider window with one out-of-range row: 1 of 5 (20%) is inside the 25%
    # per-location budget, so the good rows commit and the run is partial.
    within_window = storage_hours(5)
    within_budget = collect(
        engine,
        settings,
        hours=5,
        overrides={within_window[0]: {"temperature_2m": Decimal("842")}},
    )
    within_rows = rejection_sample(engine, within_budget.run_id)

    # The same bad row in a 3-hour window is 1 of 3 (33.3%): above the budget,
    # so the whole location is rolled back and the run fails.
    over_window = storage_hours(3)
    over_budget = collect(
        engine,
        settings,
        hours=3,
        overrides={over_window[0]: {"temperature_2m": Decimal("842")}},
    )
    over_rows = rejection_sample(engine, over_budget.run_id)

    observations = observation_sample(engine)
    watermarks = watermark_sample(engine)

    # A final run where one location is briefly unavailable.
    partial = collect(engine, settings, failing=("reykjavik-is",))
    partial_rows = rejection_sample(engine, partial.run_id)

    return [
        Sample(
            name="collection-summary.txt",
            title="One collection run, rendered exactly as `adcp collect` renders it",
            content="\n".join(
                [
                    f"$ adcp collect    # exit code {int(exit_code_for(first))}",
                    cli_text(first),
                    "",
                    f"$ adcp collect --json    # exit code {int(exit_code_for(first))}",
                    summary_json(first),
                ],
            ),
        ),
        Sample(
            name="idempotent-rerun.txt",
            title="The same window collected twice: the second run writes nothing",
            content="\n".join(
                [
                    "run 1 counters:",
                    json.dumps(first.counts.as_dict(), indent=2, sort_keys=True),
                    "",
                    "run 2 counters:",
                    json.dumps(second.counts.as_dict(), indent=2, sort_keys=True),
                    "",
                    f"stored rows after run 2: {stored_rows}",
                    "",
                    "run history (each row is one `ingestion_runs` record):",
                    first_history,
                ],
            ),
        ),
        Sample(
            name="observations.sql.txt",
            title="Stored observations, grouped per location and source (docs/queries.sql #2)",
            content=observations,
        ),
        Sample(
            name="watermarks.sql.txt",
            title="Per-location cursors after the runs (docs/queries.sql #1)",
            content=watermarks,
        ),
        Sample(
            name="rejection-result.txt",
            title="One out-of-range row: inside the budget it is a partial run; "
            "over the budget it fails the location",
            content="\n".join(
                [
                    "within budget - 1 of 5 rows rejected (20% <= 25%):",
                    f"status: {within_budget.status.value} "
                    f"(exit code {int(exit_code_for(within_budget))})",
                    json.dumps(within_budget.counts.as_dict(), indent=2, sort_keys=True),
                    "",
                    "ingestion_run_errors rows for that run:",
                    within_rows,
                    "",
                    "",
                    "above budget - 1 of 3 rows rejected (33% > 25%):",
                    f"status: {over_budget.status.value} "
                    f"(exit code {int(exit_code_for(over_budget))})",
                    json.dumps(over_budget.counts.as_dict(), indent=2, sort_keys=True),
                    "",
                    "ingestion_run_errors rows for that run:",
                    over_rows,
                ],
            ),
        ),
        Sample(
            name="partial-failure.txt",
            title="One location fails; the other commits and the run is partial",
            content="\n".join(
                [
                    f"status: {partial.status.value} (exit code {int(exit_code_for(partial))})",
                    json.dumps(partial.counts.as_dict(), indent=2, sort_keys=True),
                    "",
                    "ingestion_run_errors rows for that run:",
                    partial_rows,
                ],
            ),
        ),
        Sample(
            name="retry-log.jsonl",
            title="Structured logs for one request: a 503, a backoff, then success",
            content=retry_sample(settings),
        ),
    ]


def normalise(content: str) -> str:
    """Strip the values that legitimately differ between runs."""
    normalised = _UUID.sub(PLACEHOLDER_RUN, content)
    normalised = _TIMESTAMP.sub('"timestamp": "<normalised>"', normalised)
    return _DURATION.sub('"duration_ms": "<normalised>"', normalised)


def write_or_check(samples: list[Sample], output: Path, *, check: bool) -> int:
    stale: list[str] = []
    for sample in samples:
        rendered = normalise(sample.render())
        path = output / sample.name
        if check:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing != rendered:
                stale.append(str(path))
            continue
        output.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        print(f"wrote {path}", file=sys.stderr)
    if check:
        if stale:
            print("stale samples (rerun scripts/capture_samples.py):", file=sys.stderr)
            for stale_path in stale:
                print(f"  {stale_path}", file=sys.stderr)
            return 1
        print(f"{len(samples)} samples are up to date", file=sys.stderr)
    return 0


def main() -> int:
    arguments = parse_arguments()
    settings = Settings()
    base_url = str(settings.database_url)
    scratch = scratch_url(base_url)
    name = sa.engine.make_url(scratch).database or "adcp_samples"
    create_scratch_database(base_url, name)
    dispose_engine()
    try:
        upgrade(database_url=scratch, connect_timeout_s=5)
        scenario = scenario_settings(scratch)
        engine = create_engine_from_settings(scenario)
        try:
            samples = build_samples(engine, scenario)
        finally:
            engine.dispose()
        print(f"database used: {PLACEHOLDER_DSN}", file=sys.stderr)
        return write_or_check(samples, arguments.output, check=arguments.check)
    finally:
        drop_scratch_database(base_url, name)


if __name__ == "__main__":
    raise SystemExit(main())
